name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Upload SSH key
      uses: webfactory/ssh-agent@v0.4.2
      with:
        ssh-private-key: ${{ secrets.GH_RUNNER_SSH_PRIVATE_KEY }}

    - name: Copy SSH Key
      run: echo "${{ secrets.GH_RUNNER_SSH_PRIVATE_KEY }}" > ssh_key.pem

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform Changes
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}