name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Copy SSH Key
      run: echo "${{ secrets.GH_RUNNER_SSH_PRIVATE_KEY }}" > ssh_key.pem

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform Changes
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Capture Terraform Outputs
      id: terraform_outputs
      run: echo "::set-output name=ping_results::$(terraform output ping_results)"
  
    - name: Display Outputs
      run: echo "Output ${{ steps.terraform_outputs.outputs.ping_results }}"